name: aris
base: core18
version: '2.2'
summary: A logical proof program
license: GPL-3.0
contact: zoltan@geogebra.org
source-code: https://github.com/kovzol/aris.git
website: https://www.gnu.org/software/aris/
icon: src/icon.png

description: |
  Aris supports propositional and predicate logic, Boolean algebra,
  and arithmetical logic in the form of abstract sequences (seqlog).

grade: stable
confinement: strict

apps:
  aris:
    command: bin/aris
    plugs:
      - home
      - x11
    extensions:
      - gnome-3-28

parts:
  aris:
    build-packages: [cmake, build-essential, pkg-config, libgtk-3-dev, libxml2-dev]
    source: https://github.com/kovzol/aris.git
    plugin: cmake
    stage-packages:
      - libgtk-3-0
      - libxml2
